---
name: Run-perf CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  selftests:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 500
      - name: Fetch tags required to get version
        run: git fetch --tags --depth 500
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install ".[dev]"
      - run: make check
